plugins:
  - serverless-leo

service: hello-serverless-leo-php-world

provider:
  name: aws
  runtime: python3.7
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  stackName: ${self:provider.stage}-${self:service}

custom:
  dev:
    leoStack: TestBus
  test:
    leoStack: TestBus

functions:
  helloPythonWorld:
    handler: index.handler
    memorySize: 128
    timeout: 10
    events:
      - leo: test_hello

# AWS has a cron event scheduler for lambda https://serverless.com/framework/docs/providers/aws/events/schedule/
