[package]
name = "NAME_TOKEN"
version = "0.1.0"
authors = ["NAME_HERE"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"

#lambda runtime
lambda = { git = "https://github.com/awslabs/aws-lambda-rust-runtime/", rev = "5ae037ef9ffabdac5a2cfcd22cd2c090e104e914" }
tokio = { version = "1.4.0", features = ["full"] }
